# Refactor module & rename: *svs_file_to_patches_tfrecord(...)*
## Outline Unit Test for stable functions

In [5]:
import os
import sys

import numpy as np

def get_fence_array(patch_length, overall_length):
    """ create a left-right set of pairs that descrete overall_length into patch_length segments
    Usage: fence_array = get_fence_array(patch_length, overall_length)
    
    Args:
        patch_length:   patch size - number of pixels high or wide 
        patch_length:   overall number of pixels high or wide 
        
    Returns:
        fence_array:    boundry values for each segment
        -----------:    [[left_0, right_0], 
                         [left_1, right_1], 
                         [left_2, right_2],... ]
    """
    # Determine the array size
    n_fenced = overall_length // patch_length       # number of boxes
    n_remain = 1 + overall_length % patch_length    # number of pixels leftover
    paddit = n_remain // 2                          # padding for the beginning
    
    if n_remain == patch_length:                    # exact fit special case: exactly one left over
        paddit = 0
        # n_remain = 0
        n_fenced = n_fenced + 1
    
    # Allocate as integers for use as indices
    fence_array = np.zeros((n_fenced, 2)).astype(int)
    for k in range(n_fenced):
        # for each box edge, get the beginning and end pixel location
        if k == 0:
            # first case special (padding)
            fence_array[k, 0] = paddit
            # add the width to it
            fence_array[k, 1] = fence_array[k, 0] + patch_length - 1
            
        elif fence_array[k-1, 1] + patch_length <= overall_length:
            # Previous right pixel plus one 
            fence_array[k, 0] = fence_array[k-1, 1] + 1
            # add the width to it
            fence_array[k, 1] = fence_array[k, 0] + patch_length - 1
            
                
    return fence_array


In [6]:
"""             Create Unit Test Data for
                fence_array = get_fence_array(patch_length, overall_length)
"""
#                     Even divisor test
patch_length = 10
overall_length = 100

print('\tEven divisor test:\n\tDivide %i pixels into %i bounds\n'%(overall_length, patch_length))
fence_array = get_fence_array(patch_length, overall_length)

print(type(fence_array), fence_array)


	Even divisor test:
	Divide 100 pixels into 10 bounds

<class 'numpy.ndarray'> [[ 0  9]
 [10 19]
 [20 29]
 [30 39]
 [40 49]
 [50 59]
 [60 69]
 [70 79]
 [80 89]
 [90 99]]


In [4]:
length_factors = [2,3,5]
length = np.array(length_factors).prod() - 1
print('\n  length: %i, range = (0, %i)\n'%(length + 1, length))
for k in length_factors:
    print('divisor: ', k, '\n', get_fence_array(k, length))


  length: 30, range = (0, 29)

divisor:  2 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]
divisor:  3 
 [[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]
 [12 14]
 [15 17]
 [18 20]
 [21 23]
 [24 26]
 [27 29]]
divisor:  5 
 [[ 0  4]
 [ 5  9]
 [10 14]
 [15 19]
 [20 24]
 [25 29]]


In [4]:
length_factors = [2,3,5]
length = np.array(length_factors).prod() - (length_factors[0]) - 1
print('\n  length: %i, range = (0, %i)\n'%(length + 1, length))
for k in length_factors:
    print('divisor: ', k, '\n', get_fence_array(k, length))
    
length = np.array(length_factors).prod() - (length_factors[1]) - 1
print('\n  length: %i, range = (0, %i)\n'%(length + 1, length))
for k in length_factors:
    print('divisor: ', k, '\n', get_fence_array(k, length))
    
length = np.array(length_factors).prod() - (length_factors[1]) - 1
print('\n  length: %i, range = (0, %i)\n'%(length + 1, length))
for k in length_factors:
    print('divisor: ', k, '\n', get_fence_array(k, length))


  length: 28, range = (0, 27)

divisor:  2 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]]
divisor:  3 
 [[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]
 [12 14]
 [15 17]
 [18 20]
 [21 23]
 [24 26]]
divisor:  5 
 [[ 1  5]
 [ 6 10]
 [11 15]
 [16 20]
 [21 25]]

  length: 27, range = (0, 26)

divisor:  2 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]]
divisor:  3 
 [[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]
 [12 14]
 [15 17]
 [18 20]
 [21 23]
 [24 26]]
divisor:  5 
 [[ 1  5]
 [ 6 10]
 [11 15]
 [16 20]
 [21 25]]

  length: 27, range = (0, 26)

divisor:  2 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]]
divisor:  3 
 [[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]
 [12 14]
 [15 17]
 [18 20]
 [21 23]
 [24 26]]
divisor:  5 
 [[ 1  5]
 [ 6 10]
 [11 15]
 [16 20]
 [21 25]]
