# Examine multi-processing / paralell execution option
    * result - may not be worth the effort because file writes may clash & hang
    
****
## scipy image: cleaning, segmentation, etc.
[API Reference: scikit-image](https://scikit-image.org/docs/dev/api/api.html) <br>
****
[Home: scikit-image aka skimage](https://scikit-image.org/) <br>
[Documentation: scikit-image](https://scikit-image.org/docs/stable/) <br>
[scikit-image on GitHub](https://github.com/scikit-image/scikit-image) <br>
[User Guide: scikit-image](https://scikit-image.org/docs/dev/user_guide) <br>
[Founder-tutor](https://bids.berkeley.edu/resources/videos/scikit-image-image-analysis-python-intermediate) <br>
****
## OpenSlide:
[OpenSlide Wiki](https://github.com/openslide/openslide/wiki) <br>
[OpenSlide api](https://openslide.org/api/python/) <br>
[openslide github](https://github.com/openslide/openslide-python) <br>
[openslide dot org](https://openslide.org/) <br>
[openslide C docs](https://openslide.org/api/openslide_8h.html) <br>

In [1]:
# import tempfile

# dirpath = tempfile.mkdtemp()
# if os.path.isdir(dirpath):
#     print(dirpath)
#     os.rmdir(dirpath)
#     print('directory still exists = ',os.path.isdir(dirpath))

In [2]:
import os
import time
import glob
import math
import multiprocessing as mp
import itertools
import hashlib
import tempfile

import numpy as np
import openslide
from skimage.filters import threshold_otsu

import PIL

output_dir = '../../DigiPath_MLTK_data/out_to_test'
if os.path.isdir(output_dir) == False:
    os.makedirs(output_dir)
    
OUTPUT_PATH = output_dir
data_dir = '../../DigiPath_MLTK_data/Aperio'
files_list = ['CMU-1-Small-Region.svs', 'CMU-1.svs']
SVS = os.path.join(data_dir, files_list[0])
print('Working with file:', SVS, '\nOutput path:', OUTPUT_PATH)

Working with file: ../../DigiPath_MLTK_data/Aperio/CMU-1-Small-Region.svs 
Output path: ../../DigiPath_MLTK_data/out_to_test


In [3]:
out_dir = '../../DigiPath_MLTK_data/out_to_test'
file_types = ['.jpg']
files_list = []
for maybe_file in os.listdir(out_dir):
    full_path = os.path.join(out_dir, maybe_file)
    if os.path.isfile(full_path):
        _, f_ext = os.path.splitext(maybe_file)
        if f_ext in file_types:
            files_list.append(full_path)

print(len(files_list))

999


In [4]:
"""                                                Serial time test
need to know what size the pre-trained models used
& graphic file types preferred by tensorflow (float, float32, int, etc)
"""
PATCH_HEIGHT = 256
PATCH_WIDTH = 256

t0 = time.time()
# open the file
test_file_name = os.path.join(data_dir, 'CMU-1.svs')
print('Opening Image file: \n\t{}\n'.format(test_file_name))
os_obj = openslide.OpenSlide(test_file_name)
pixels_height = os_obj.dimensions[0]
pixels_width = os_obj.dimensions[1]

print('Image is {} x {}\n{} pixels'.format(pixels_height, 
                                           pixels_width, 
                                           pixels_height * pixels_width))

# read the meta data
pixels_height_ds = os_obj.level_dimensions[-1][0]
pixels_width_ds = os_obj.level_dimensions[-1][1]
print(pixels_height_ds, pixels_width_ds)

# find the thumbnail size ratio (need pre-trained size)
print(pixels_height / pixels_height_ds, pixels_width / pixels_width_ds)
print('obj.level_downsamples', os_obj.level_downsamples)
print('obj.level_downsamples[-1]', os_obj.level_downsamples[-1])

big_thumb = os_obj.get_thumbnail((pixels_height_ds, pixels_width_ds))
print(type(big_thumb), big_thumb.size, big_thumb.getextrema())

# make the mask
grey_thumbnail = np.array(big_thumb.convert('L'))
thresh = threshold_otsu(grey_thumbnail)
mask = np.array(grey_thumbnail) < thresh
mask_im = PIL.Image.fromarray(np.uint8(mask) * 255)
# display(mask_im)

# make the grid
grid_height = pixels_height // PATCH_HEIGHT
grid_width = pixels_width // PATCH_WIDTH
print('\n%40s: %5i, %5i'%('grid size', grid_height, grid_width))
print('%40s: %5i, %5i'%('full size cells',PATCH_HEIGHT, PATCH_WIDTH))
thumb_cell_height = pixels_height_ds // grid_height
thumb_cell_width = pixels_width_ds // grid_width
print('%40s: %5i, %5i'%('thumb cells',thumb_cell_height, thumb_cell_width))

# make the directory
_, f_name = os.path.split(test_file_name)
f_name, f_ext = os.path.splitext(f_name)
print('directory name',f_name)

# get the ndarrays of full size grid, write as type
zoom_up_ratio = 16
for grid_row in range(grid_height):
    for grid_col in range(grid_width):
        h_idx_start = grid_row * thumb_cell_height
        h_idx_end = (grid_row + 1) * thumb_cell_height
        w_idx_start = grid_col * thumb_cell_width
        w_idx_end = (grid_col + 1) * thumb_cell_width
        
        big_idx = np.array([h_idx_start,h_idx_end,w_idx_start,w_idx_end])*zoom_up_ratio
        print(h_idx_start, h_idx_end, w_idx_start, w_idx_end, '\n\t', big_idx)
        
print('\nthumb size:', pixels_height_ds, pixels_width_ds)
print('\nfull size:', pixels_height, pixels_width)

# (save a list of files)

print('\ncell run time', time.time() - t0)

Opening Image file: 
	../../DigiPath_MLTK_data/Aperio/CMU-1.svs

Image is 46000 x 32914
1514044000 pixels
2875 2057
16.0 16.000972289742343
obj.level_downsamples (1.0, 4.000121536217793, 16.00048614487117)
obj.level_downsamples[-1] 16.00048614487117
<class 'PIL.Image.Image'> (2875, 2057) ((0, 255), (0, 255), (3, 255))

                               grid size:   179,   128
                         full size cells:   256,   256
                             thumb cells:    16,    16
directory name CMU-1
0 16 0 16 
	 [  0 256   0 256]
0 16 16 32 
	 [  0 256 256 512]
0 16 32 48 
	 [  0 256 512 768]
0 16 48 64 
	 [   0  256  768 1024]
0 16 64 80 
	 [   0  256 1024 1280]
0 16 80 96 
	 [   0  256 1280 1536]
0 16 96 112 
	 [   0  256 1536 1792]
0 16 112 128 
	 [   0  256 1792 2048]
0 16 128 144 
	 [   0  256 2048 2304]
0 16 144 160 
	 [   0  256 2304 2560]
0 16 160 176 
	 [   0  256 2560 2816]
0 16 176 192 
	 [   0  256 2816 3072]
0 16 192 208 
	 [   0  256 3072 3328]
0 16 208 224 
	 [   0  25

32 48 1088 1104 
	 [  512   768 17408 17664]
32 48 1104 1120 
	 [  512   768 17664 17920]
32 48 1120 1136 
	 [  512   768 17920 18176]
32 48 1136 1152 
	 [  512   768 18176 18432]
32 48 1152 1168 
	 [  512   768 18432 18688]
32 48 1168 1184 
	 [  512   768 18688 18944]
32 48 1184 1200 
	 [  512   768 18944 19200]
32 48 1200 1216 
	 [  512   768 19200 19456]
32 48 1216 1232 
	 [  512   768 19456 19712]
32 48 1232 1248 
	 [  512   768 19712 19968]
32 48 1248 1264 
	 [  512   768 19968 20224]
32 48 1264 1280 
	 [  512   768 20224 20480]
32 48 1280 1296 
	 [  512   768 20480 20736]
32 48 1296 1312 
	 [  512   768 20736 20992]
32 48 1312 1328 
	 [  512   768 20992 21248]
32 48 1328 1344 
	 [  512   768 21248 21504]
32 48 1344 1360 
	 [  512   768 21504 21760]
32 48 1360 1376 
	 [  512   768 21760 22016]
32 48 1376 1392 
	 [  512   768 22016 22272]
32 48 1392 1408 
	 [  512   768 22272 22528]
32 48 1408 1424 
	 [  512   768 22528 22784]
32 48 1424 1440 
	 [  512   768 22784 23040]
32 48 1440

80 96 272 288 
	 [1280 1536 4352 4608]
80 96 288 304 
	 [1280 1536 4608 4864]
80 96 304 320 
	 [1280 1536 4864 5120]
80 96 320 336 
	 [1280 1536 5120 5376]
80 96 336 352 
	 [1280 1536 5376 5632]
80 96 352 368 
	 [1280 1536 5632 5888]
80 96 368 384 
	 [1280 1536 5888 6144]
80 96 384 400 
	 [1280 1536 6144 6400]
80 96 400 416 
	 [1280 1536 6400 6656]
80 96 416 432 
	 [1280 1536 6656 6912]
80 96 432 448 
	 [1280 1536 6912 7168]
80 96 448 464 
	 [1280 1536 7168 7424]
80 96 464 480 
	 [1280 1536 7424 7680]
80 96 480 496 
	 [1280 1536 7680 7936]
80 96 496 512 
	 [1280 1536 7936 8192]
80 96 512 528 
	 [1280 1536 8192 8448]
80 96 528 544 
	 [1280 1536 8448 8704]
80 96 544 560 
	 [1280 1536 8704 8960]
80 96 560 576 
	 [1280 1536 8960 9216]
80 96 576 592 
	 [1280 1536 9216 9472]
80 96 592 608 
	 [1280 1536 9472 9728]
80 96 608 624 
	 [1280 1536 9728 9984]
80 96 624 640 
	 [ 1280  1536  9984 10240]
80 96 640 656 
	 [ 1280  1536 10240 10496]
80 96 656 672 
	 [ 1280  1536 10496 10752]
80 96 672 688

	 [ 2048  2304 12544 12800]
128 144 800 816 
	 [ 2048  2304 12800 13056]
128 144 816 832 
	 [ 2048  2304 13056 13312]
128 144 832 848 
	 [ 2048  2304 13312 13568]
128 144 848 864 
	 [ 2048  2304 13568 13824]
128 144 864 880 
	 [ 2048  2304 13824 14080]
128 144 880 896 
	 [ 2048  2304 14080 14336]
128 144 896 912 
	 [ 2048  2304 14336 14592]
128 144 912 928 
	 [ 2048  2304 14592 14848]
128 144 928 944 
	 [ 2048  2304 14848 15104]
128 144 944 960 
	 [ 2048  2304 15104 15360]
128 144 960 976 
	 [ 2048  2304 15360 15616]
128 144 976 992 
	 [ 2048  2304 15616 15872]
128 144 992 1008 
	 [ 2048  2304 15872 16128]
128 144 1008 1024 
	 [ 2048  2304 16128 16384]
128 144 1024 1040 
	 [ 2048  2304 16384 16640]
128 144 1040 1056 
	 [ 2048  2304 16640 16896]
128 144 1056 1072 
	 [ 2048  2304 16896 17152]
128 144 1072 1088 
	 [ 2048  2304 17152 17408]
128 144 1088 1104 
	 [ 2048  2304 17408 17664]
128 144 1104 1120 
	 [ 2048  2304 17664 17920]
128 144 1120 1136 
	 [ 2048  2304 17920 18176]
128 144 11

	 [2816 3072 5376 5632]
176 192 352 368 
	 [2816 3072 5632 5888]
176 192 368 384 
	 [2816 3072 5888 6144]
176 192 384 400 
	 [2816 3072 6144 6400]
176 192 400 416 
	 [2816 3072 6400 6656]
176 192 416 432 
	 [2816 3072 6656 6912]
176 192 432 448 
	 [2816 3072 6912 7168]
176 192 448 464 
	 [2816 3072 7168 7424]
176 192 464 480 
	 [2816 3072 7424 7680]
176 192 480 496 
	 [2816 3072 7680 7936]
176 192 496 512 
	 [2816 3072 7936 8192]
176 192 512 528 
	 [2816 3072 8192 8448]
176 192 528 544 
	 [2816 3072 8448 8704]
176 192 544 560 
	 [2816 3072 8704 8960]
176 192 560 576 
	 [2816 3072 8960 9216]
176 192 576 592 
	 [2816 3072 9216 9472]
176 192 592 608 
	 [2816 3072 9472 9728]
176 192 608 624 
	 [2816 3072 9728 9984]
176 192 624 640 
	 [ 2816  3072  9984 10240]
176 192 640 656 
	 [ 2816  3072 10240 10496]
176 192 656 672 
	 [ 2816  3072 10496 10752]
176 192 672 688 
	 [ 2816  3072 10752 11008]
176 192 688 704 
	 [ 2816  3072 11008 11264]
176 192 704 720 
	 [ 2816  3072 11264 11520]
176 192 7

	 [3584 3840 7936 8192]
224 240 512 528 
	 [3584 3840 8192 8448]
224 240 528 544 
	 [3584 3840 8448 8704]
224 240 544 560 
	 [3584 3840 8704 8960]
224 240 560 576 
	 [3584 3840 8960 9216]
224 240 576 592 
	 [3584 3840 9216 9472]
224 240 592 608 
	 [3584 3840 9472 9728]
224 240 608 624 
	 [3584 3840 9728 9984]
224 240 624 640 
	 [ 3584  3840  9984 10240]
224 240 640 656 
	 [ 3584  3840 10240 10496]
224 240 656 672 
	 [ 3584  3840 10496 10752]
224 240 672 688 
	 [ 3584  3840 10752 11008]
224 240 688 704 
	 [ 3584  3840 11008 11264]
224 240 704 720 
	 [ 3584  3840 11264 11520]
224 240 720 736 
	 [ 3584  3840 11520 11776]
224 240 736 752 
	 [ 3584  3840 11776 12032]
224 240 752 768 
	 [ 3584  3840 12032 12288]
224 240 768 784 
	 [ 3584  3840 12288 12544]
224 240 784 800 
	 [ 3584  3840 12544 12800]
224 240 800 816 
	 [ 3584  3840 12800 13056]
224 240 816 832 
	 [ 3584  3840 13056 13312]
224 240 832 848 
	 [ 3584  3840 13312 13568]
224 240 848 864 
	 [ 3584  3840 13568 13824]
224 240 864 88

272 288 1024 1040 
	 [ 4352  4608 16384 16640]
272 288 1040 1056 
	 [ 4352  4608 16640 16896]
272 288 1056 1072 
	 [ 4352  4608 16896 17152]
272 288 1072 1088 
	 [ 4352  4608 17152 17408]
272 288 1088 1104 
	 [ 4352  4608 17408 17664]
272 288 1104 1120 
	 [ 4352  4608 17664 17920]
272 288 1120 1136 
	 [ 4352  4608 17920 18176]
272 288 1136 1152 
	 [ 4352  4608 18176 18432]
272 288 1152 1168 
	 [ 4352  4608 18432 18688]
272 288 1168 1184 
	 [ 4352  4608 18688 18944]
272 288 1184 1200 
	 [ 4352  4608 18944 19200]
272 288 1200 1216 
	 [ 4352  4608 19200 19456]
272 288 1216 1232 
	 [ 4352  4608 19456 19712]
272 288 1232 1248 
	 [ 4352  4608 19712 19968]
272 288 1248 1264 
	 [ 4352  4608 19968 20224]
272 288 1264 1280 
	 [ 4352  4608 20224 20480]
272 288 1280 1296 
	 [ 4352  4608 20480 20736]
272 288 1296 1312 
	 [ 4352  4608 20736 20992]
272 288 1312 1328 
	 [ 4352  4608 20992 21248]
272 288 1328 1344 
	 [ 4352  4608 21248 21504]
272 288 1344 1360 
	 [ 4352  4608 21504 21760]
272 288 1360 

	 [ 5120  5376 24576 24832]
320 336 1552 1568 
	 [ 5120  5376 24832 25088]
320 336 1568 1584 
	 [ 5120  5376 25088 25344]
320 336 1584 1600 
	 [ 5120  5376 25344 25600]
320 336 1600 1616 
	 [ 5120  5376 25600 25856]
320 336 1616 1632 
	 [ 5120  5376 25856 26112]
320 336 1632 1648 
	 [ 5120  5376 26112 26368]
320 336 1648 1664 
	 [ 5120  5376 26368 26624]
320 336 1664 1680 
	 [ 5120  5376 26624 26880]
320 336 1680 1696 
	 [ 5120  5376 26880 27136]
320 336 1696 1712 
	 [ 5120  5376 27136 27392]
320 336 1712 1728 
	 [ 5120  5376 27392 27648]
320 336 1728 1744 
	 [ 5120  5376 27648 27904]
320 336 1744 1760 
	 [ 5120  5376 27904 28160]
320 336 1760 1776 
	 [ 5120  5376 28160 28416]
320 336 1776 1792 
	 [ 5120  5376 28416 28672]
320 336 1792 1808 
	 [ 5120  5376 28672 28928]
320 336 1808 1824 
	 [ 5120  5376 28928 29184]
320 336 1824 1840 
	 [ 5120  5376 29184 29440]
320 336 1840 1856 
	 [ 5120  5376 29440 29696]
320 336 1856 1872 
	 [ 5120  5376 29696 29952]
320 336 1872 1888 
	 [ 5120  537

384 400 16 32 
	 [6144 6400  256  512]
384 400 32 48 
	 [6144 6400  512  768]
384 400 48 64 
	 [6144 6400  768 1024]
384 400 64 80 
	 [6144 6400 1024 1280]
384 400 80 96 
	 [6144 6400 1280 1536]
384 400 96 112 
	 [6144 6400 1536 1792]
384 400 112 128 
	 [6144 6400 1792 2048]
384 400 128 144 
	 [6144 6400 2048 2304]
384 400 144 160 
	 [6144 6400 2304 2560]
384 400 160 176 
	 [6144 6400 2560 2816]
384 400 176 192 
	 [6144 6400 2816 3072]
384 400 192 208 
	 [6144 6400 3072 3328]
384 400 208 224 
	 [6144 6400 3328 3584]
384 400 224 240 
	 [6144 6400 3584 3840]
384 400 240 256 
	 [6144 6400 3840 4096]
384 400 256 272 
	 [6144 6400 4096 4352]
384 400 272 288 
	 [6144 6400 4352 4608]
384 400 288 304 
	 [6144 6400 4608 4864]
384 400 304 320 
	 [6144 6400 4864 5120]
384 400 320 336 
	 [6144 6400 5120 5376]
384 400 336 352 
	 [6144 6400 5376 5632]
384 400 352 368 
	 [6144 6400 5632 5888]
384 400 368 384 
	 [6144 6400 5888 6144]
384 400 384 400 
	 [6144 6400 6144 6400]
384 400 400 416 
	 [6144 64

432 448 544 560 
	 [6912 7168 8704 8960]
432 448 560 576 
	 [6912 7168 8960 9216]
432 448 576 592 
	 [6912 7168 9216 9472]
432 448 592 608 
	 [6912 7168 9472 9728]
432 448 608 624 
	 [6912 7168 9728 9984]
432 448 624 640 
	 [ 6912  7168  9984 10240]
432 448 640 656 
	 [ 6912  7168 10240 10496]
432 448 656 672 
	 [ 6912  7168 10496 10752]
432 448 672 688 
	 [ 6912  7168 10752 11008]
432 448 688 704 
	 [ 6912  7168 11008 11264]
432 448 704 720 
	 [ 6912  7168 11264 11520]
432 448 720 736 
	 [ 6912  7168 11520 11776]
432 448 736 752 
	 [ 6912  7168 11776 12032]
432 448 752 768 
	 [ 6912  7168 12032 12288]
432 448 768 784 
	 [ 6912  7168 12288 12544]
432 448 784 800 
	 [ 6912  7168 12544 12800]
432 448 800 816 
	 [ 6912  7168 12800 13056]
432 448 816 832 
	 [ 6912  7168 13056 13312]
432 448 832 848 
	 [ 6912  7168 13312 13568]
432 448 848 864 
	 [ 6912  7168 13568 13824]
432 448 864 880 
	 [ 6912  7168 13824 14080]
432 448 880 896 
	 [ 6912  7168 14080 14336]
432 448 896 912 
	 [ 6912  716

480 496 1056 1072 
	 [ 7680  7936 16896 17152]
480 496 1072 1088 
	 [ 7680  7936 17152 17408]
480 496 1088 1104 
	 [ 7680  7936 17408 17664]
480 496 1104 1120 
	 [ 7680  7936 17664 17920]
480 496 1120 1136 
	 [ 7680  7936 17920 18176]
480 496 1136 1152 
	 [ 7680  7936 18176 18432]
480 496 1152 1168 
	 [ 7680  7936 18432 18688]
480 496 1168 1184 
	 [ 7680  7936 18688 18944]
480 496 1184 1200 
	 [ 7680  7936 18944 19200]
480 496 1200 1216 
	 [ 7680  7936 19200 19456]
480 496 1216 1232 
	 [ 7680  7936 19456 19712]
480 496 1232 1248 
	 [ 7680  7936 19712 19968]
480 496 1248 1264 
	 [ 7680  7936 19968 20224]
480 496 1264 1280 
	 [ 7680  7936 20224 20480]
480 496 1280 1296 
	 [ 7680  7936 20480 20736]
480 496 1296 1312 
	 [ 7680  7936 20736 20992]
480 496 1312 1328 
	 [ 7680  7936 20992 21248]
480 496 1328 1344 
	 [ 7680  7936 21248 21504]
480 496 1344 1360 
	 [ 7680  7936 21504 21760]
480 496 1360 1376 
	 [ 7680  7936 21760 22016]
480 496 1376 1392 
	 [ 7680  7936 22016 22272]
480 496 1392 

544 560 240 256 
	 [8704 8960 3840 4096]
544 560 256 272 
	 [8704 8960 4096 4352]
544 560 272 288 
	 [8704 8960 4352 4608]
544 560 288 304 
	 [8704 8960 4608 4864]
544 560 304 320 
	 [8704 8960 4864 5120]
544 560 320 336 
	 [8704 8960 5120 5376]
544 560 336 352 
	 [8704 8960 5376 5632]
544 560 352 368 
	 [8704 8960 5632 5888]
544 560 368 384 
	 [8704 8960 5888 6144]
544 560 384 400 
	 [8704 8960 6144 6400]
544 560 400 416 
	 [8704 8960 6400 6656]
544 560 416 432 
	 [8704 8960 6656 6912]
544 560 432 448 
	 [8704 8960 6912 7168]
544 560 448 464 
	 [8704 8960 7168 7424]
544 560 464 480 
	 [8704 8960 7424 7680]
544 560 480 496 
	 [8704 8960 7680 7936]
544 560 496 512 
	 [8704 8960 7936 8192]
544 560 512 528 
	 [8704 8960 8192 8448]
544 560 528 544 
	 [8704 8960 8448 8704]
544 560 544 560 
	 [8704 8960 8704 8960]
544 560 560 576 
	 [8704 8960 8960 9216]
544 560 576 592 
	 [8704 8960 9216 9472]
544 560 592 608 
	 [8704 8960 9472 9728]
544 560 608 624 
	 [8704 8960 9728 9984]
544 560 624 640 

592 608 384 400 
	 [9472 9728 6144 6400]
592 608 400 416 
	 [9472 9728 6400 6656]
592 608 416 432 
	 [9472 9728 6656 6912]
592 608 432 448 
	 [9472 9728 6912 7168]
592 608 448 464 
	 [9472 9728 7168 7424]
592 608 464 480 
	 [9472 9728 7424 7680]
592 608 480 496 
	 [9472 9728 7680 7936]
592 608 496 512 
	 [9472 9728 7936 8192]
592 608 512 528 
	 [9472 9728 8192 8448]
592 608 528 544 
	 [9472 9728 8448 8704]
592 608 544 560 
	 [9472 9728 8704 8960]
592 608 560 576 
	 [9472 9728 8960 9216]
592 608 576 592 
	 [9472 9728 9216 9472]
592 608 592 608 
	 [9472 9728 9472 9728]
592 608 608 624 
	 [9472 9728 9728 9984]
592 608 624 640 
	 [ 9472  9728  9984 10240]
592 608 640 656 
	 [ 9472  9728 10240 10496]
592 608 656 672 
	 [ 9472  9728 10496 10752]
592 608 672 688 
	 [ 9472  9728 10752 11008]
592 608 688 704 
	 [ 9472  9728 11008 11264]
592 608 704 720 
	 [ 9472  9728 11264 11520]
592 608 720 736 
	 [ 9472  9728 11520 11776]
592 608 736 752 
	 [ 9472  9728 11776 12032]
592 608 752 768 
	 [ 9472

	 [ 9984 10240 28928 29184]
624 640 1824 1840 
	 [ 9984 10240 29184 29440]
624 640 1840 1856 
	 [ 9984 10240 29440 29696]
624 640 1856 1872 
	 [ 9984 10240 29696 29952]
624 640 1872 1888 
	 [ 9984 10240 29952 30208]
624 640 1888 1904 
	 [ 9984 10240 30208 30464]
624 640 1904 1920 
	 [ 9984 10240 30464 30720]
624 640 1920 1936 
	 [ 9984 10240 30720 30976]
624 640 1936 1952 
	 [ 9984 10240 30976 31232]
624 640 1952 1968 
	 [ 9984 10240 31232 31488]
624 640 1968 1984 
	 [ 9984 10240 31488 31744]
624 640 1984 2000 
	 [ 9984 10240 31744 32000]
624 640 2000 2016 
	 [ 9984 10240 32000 32256]
624 640 2016 2032 
	 [ 9984 10240 32256 32512]
624 640 2032 2048 
	 [ 9984 10240 32512 32768]
640 656 0 16 
	 [10240 10496     0   256]
640 656 16 32 
	 [10240 10496   256   512]
640 656 32 48 
	 [10240 10496   512   768]
640 656 48 64 
	 [10240 10496   768  1024]
640 656 64 80 
	 [10240 10496  1024  1280]
640 656 80 96 
	 [10240 10496  1280  1536]
640 656 96 112 
	 [10240 10496  1536  1792]
640 656 112 1

	 [11008 11264  6912  7168]
688 704 448 464 
	 [11008 11264  7168  7424]
688 704 464 480 
	 [11008 11264  7424  7680]
688 704 480 496 
	 [11008 11264  7680  7936]
688 704 496 512 
	 [11008 11264  7936  8192]
688 704 512 528 
	 [11008 11264  8192  8448]
688 704 528 544 
	 [11008 11264  8448  8704]
688 704 544 560 
	 [11008 11264  8704  8960]
688 704 560 576 
	 [11008 11264  8960  9216]
688 704 576 592 
	 [11008 11264  9216  9472]
688 704 592 608 
	 [11008 11264  9472  9728]
688 704 608 624 
	 [11008 11264  9728  9984]
688 704 624 640 
	 [11008 11264  9984 10240]
688 704 640 656 
	 [11008 11264 10240 10496]
688 704 656 672 
	 [11008 11264 10496 10752]
688 704 672 688 
	 [11008 11264 10752 11008]
688 704 688 704 
	 [11008 11264 11008 11264]
688 704 704 720 
	 [11008 11264 11264 11520]
688 704 720 736 
	 [11008 11264 11520 11776]
688 704 736 752 
	 [11008 11264 11776 12032]
688 704 752 768 
	 [11008 11264 12032 12288]
688 704 768 784 
	 [11008 11264 12288 12544]
688 704 784 800 
	 [11008 1

736 752 1616 1632 
	 [11776 12032 25856 26112]
736 752 1632 1648 
	 [11776 12032 26112 26368]
736 752 1648 1664 
	 [11776 12032 26368 26624]
736 752 1664 1680 
	 [11776 12032 26624 26880]
736 752 1680 1696 
	 [11776 12032 26880 27136]
736 752 1696 1712 
	 [11776 12032 27136 27392]
736 752 1712 1728 
	 [11776 12032 27392 27648]
736 752 1728 1744 
	 [11776 12032 27648 27904]
736 752 1744 1760 
	 [11776 12032 27904 28160]
736 752 1760 1776 
	 [11776 12032 28160 28416]
736 752 1776 1792 
	 [11776 12032 28416 28672]
736 752 1792 1808 
	 [11776 12032 28672 28928]
736 752 1808 1824 
	 [11776 12032 28928 29184]
736 752 1824 1840 
	 [11776 12032 29184 29440]
736 752 1840 1856 
	 [11776 12032 29440 29696]
736 752 1856 1872 
	 [11776 12032 29696 29952]
736 752 1872 1888 
	 [11776 12032 29952 30208]
736 752 1888 1904 
	 [11776 12032 30208 30464]
736 752 1904 1920 
	 [11776 12032 30464 30720]
736 752 1920 1936 
	 [11776 12032 30720 30976]
736 752 1936 1952 
	 [11776 12032 30976 31232]
736 752 1952 

800 816 1040 1056 
	 [12800 13056 16640 16896]
800 816 1056 1072 
	 [12800 13056 16896 17152]
800 816 1072 1088 
	 [12800 13056 17152 17408]
800 816 1088 1104 
	 [12800 13056 17408 17664]
800 816 1104 1120 
	 [12800 13056 17664 17920]
800 816 1120 1136 
	 [12800 13056 17920 18176]
800 816 1136 1152 
	 [12800 13056 18176 18432]
800 816 1152 1168 
	 [12800 13056 18432 18688]
800 816 1168 1184 
	 [12800 13056 18688 18944]
800 816 1184 1200 
	 [12800 13056 18944 19200]
800 816 1200 1216 
	 [12800 13056 19200 19456]
800 816 1216 1232 
	 [12800 13056 19456 19712]
800 816 1232 1248 
	 [12800 13056 19712 19968]
800 816 1248 1264 
	 [12800 13056 19968 20224]
800 816 1264 1280 
	 [12800 13056 20224 20480]
800 816 1280 1296 
	 [12800 13056 20480 20736]
800 816 1296 1312 
	 [12800 13056 20736 20992]
800 816 1312 1328 
	 [12800 13056 20992 21248]
800 816 1328 1344 
	 [12800 13056 21248 21504]
800 816 1344 1360 
	 [12800 13056 21504 21760]
800 816 1360 1376 
	 [12800 13056 21760 22016]
800 816 1376 

848 864 1952 1968 
	 [13568 13824 31232 31488]
848 864 1968 1984 
	 [13568 13824 31488 31744]
848 864 1984 2000 
	 [13568 13824 31744 32000]
848 864 2000 2016 
	 [13568 13824 32000 32256]
848 864 2016 2032 
	 [13568 13824 32256 32512]
848 864 2032 2048 
	 [13568 13824 32512 32768]
864 880 0 16 
	 [13824 14080     0   256]
864 880 16 32 
	 [13824 14080   256   512]
864 880 32 48 
	 [13824 14080   512   768]
864 880 48 64 
	 [13824 14080   768  1024]
864 880 64 80 
	 [13824 14080  1024  1280]
864 880 80 96 
	 [13824 14080  1280  1536]
864 880 96 112 
	 [13824 14080  1536  1792]
864 880 112 128 
	 [13824 14080  1792  2048]
864 880 128 144 
	 [13824 14080  2048  2304]
864 880 144 160 
	 [13824 14080  2304  2560]
864 880 160 176 
	 [13824 14080  2560  2816]
864 880 176 192 
	 [13824 14080  2816  3072]
864 880 192 208 
	 [13824 14080  3072  3328]
864 880 208 224 
	 [13824 14080  3328  3584]
864 880 224 240 
	 [13824 14080  3584  3840]
864 880 240 256 
	 [13824 14080  3840  4096]
864 880 256 

912 928 1216 1232 
	 [14592 14848 19456 19712]
912 928 1232 1248 
	 [14592 14848 19712 19968]
912 928 1248 1264 
	 [14592 14848 19968 20224]
912 928 1264 1280 
	 [14592 14848 20224 20480]
912 928 1280 1296 
	 [14592 14848 20480 20736]
912 928 1296 1312 
	 [14592 14848 20736 20992]
912 928 1312 1328 
	 [14592 14848 20992 21248]
912 928 1328 1344 
	 [14592 14848 21248 21504]
912 928 1344 1360 
	 [14592 14848 21504 21760]
912 928 1360 1376 
	 [14592 14848 21760 22016]
912 928 1376 1392 
	 [14592 14848 22016 22272]
912 928 1392 1408 
	 [14592 14848 22272 22528]
912 928 1408 1424 
	 [14592 14848 22528 22784]
912 928 1424 1440 
	 [14592 14848 22784 23040]
912 928 1440 1456 
	 [14592 14848 23040 23296]
912 928 1456 1472 
	 [14592 14848 23296 23552]
912 928 1472 1488 
	 [14592 14848 23552 23808]
912 928 1488 1504 
	 [14592 14848 23808 24064]
912 928 1504 1520 
	 [14592 14848 24064 24320]
912 928 1520 1536 
	 [14592 14848 24320 24576]
912 928 1536 1552 
	 [14592 14848 24576 24832]
912 928 1552 

976 992 224 240 
	 [15616 15872  3584  3840]
976 992 240 256 
	 [15616 15872  3840  4096]
976 992 256 272 
	 [15616 15872  4096  4352]
976 992 272 288 
	 [15616 15872  4352  4608]
976 992 288 304 
	 [15616 15872  4608  4864]
976 992 304 320 
	 [15616 15872  4864  5120]
976 992 320 336 
	 [15616 15872  5120  5376]
976 992 336 352 
	 [15616 15872  5376  5632]
976 992 352 368 
	 [15616 15872  5632  5888]
976 992 368 384 
	 [15616 15872  5888  6144]
976 992 384 400 
	 [15616 15872  6144  6400]
976 992 400 416 
	 [15616 15872  6400  6656]
976 992 416 432 
	 [15616 15872  6656  6912]
976 992 432 448 
	 [15616 15872  6912  7168]
976 992 448 464 
	 [15616 15872  7168  7424]
976 992 464 480 
	 [15616 15872  7424  7680]
976 992 480 496 
	 [15616 15872  7680  7936]
976 992 496 512 
	 [15616 15872  7936  8192]
976 992 512 528 
	 [15616 15872  8192  8448]
976 992 528 544 
	 [15616 15872  8448  8704]
976 992 544 560 
	 [15616 15872  8704  8960]
976 992 560 576 
	 [15616 15872  8960  9216]
976 992 57

1024 1040 752 768 
	 [16384 16640 12032 12288]
1024 1040 768 784 
	 [16384 16640 12288 12544]
1024 1040 784 800 
	 [16384 16640 12544 12800]
1024 1040 800 816 
	 [16384 16640 12800 13056]
1024 1040 816 832 
	 [16384 16640 13056 13312]
1024 1040 832 848 
	 [16384 16640 13312 13568]
1024 1040 848 864 
	 [16384 16640 13568 13824]
1024 1040 864 880 
	 [16384 16640 13824 14080]
1024 1040 880 896 
	 [16384 16640 14080 14336]
1024 1040 896 912 
	 [16384 16640 14336 14592]
1024 1040 912 928 
	 [16384 16640 14592 14848]
1024 1040 928 944 
	 [16384 16640 14848 15104]
1024 1040 944 960 
	 [16384 16640 15104 15360]
1024 1040 960 976 
	 [16384 16640 15360 15616]
1024 1040 976 992 
	 [16384 16640 15616 15872]
1024 1040 992 1008 
	 [16384 16640 15872 16128]
1024 1040 1008 1024 
	 [16384 16640 16128 16384]
1024 1040 1024 1040 
	 [16384 16640 16384 16640]
1024 1040 1040 1056 
	 [16384 16640 16640 16896]
1024 1040 1056 1072 
	 [16384 16640 16896 17152]
1024 1040 1072 1088 
	 [16384 16640 17152 17408]
10

	 [17152 17408 20224 20480]
1072 1088 1280 1296 
	 [17152 17408 20480 20736]
1072 1088 1296 1312 
	 [17152 17408 20736 20992]
1072 1088 1312 1328 
	 [17152 17408 20992 21248]
1072 1088 1328 1344 
	 [17152 17408 21248 21504]
1072 1088 1344 1360 
	 [17152 17408 21504 21760]
1072 1088 1360 1376 
	 [17152 17408 21760 22016]
1072 1088 1376 1392 
	 [17152 17408 22016 22272]
1072 1088 1392 1408 
	 [17152 17408 22272 22528]
1072 1088 1408 1424 
	 [17152 17408 22528 22784]
1072 1088 1424 1440 
	 [17152 17408 22784 23040]
1072 1088 1440 1456 
	 [17152 17408 23040 23296]
1072 1088 1456 1472 
	 [17152 17408 23296 23552]
1072 1088 1472 1488 
	 [17152 17408 23552 23808]
1072 1088 1488 1504 
	 [17152 17408 23808 24064]
1072 1088 1504 1520 
	 [17152 17408 24064 24320]
1072 1088 1520 1536 
	 [17152 17408 24320 24576]
1072 1088 1536 1552 
	 [17152 17408 24576 24832]
1072 1088 1552 1568 
	 [17152 17408 24832 25088]
1072 1088 1568 1584 
	 [17152 17408 25088 25344]
1072 1088 1584 1600 
	 [17152 17408 25344

1136 1152 896 912 
	 [18176 18432 14336 14592]
1136 1152 912 928 
	 [18176 18432 14592 14848]
1136 1152 928 944 
	 [18176 18432 14848 15104]
1136 1152 944 960 
	 [18176 18432 15104 15360]
1136 1152 960 976 
	 [18176 18432 15360 15616]
1136 1152 976 992 
	 [18176 18432 15616 15872]
1136 1152 992 1008 
	 [18176 18432 15872 16128]
1136 1152 1008 1024 
	 [18176 18432 16128 16384]
1136 1152 1024 1040 
	 [18176 18432 16384 16640]
1136 1152 1040 1056 
	 [18176 18432 16640 16896]
1136 1152 1056 1072 
	 [18176 18432 16896 17152]
1136 1152 1072 1088 
	 [18176 18432 17152 17408]
1136 1152 1088 1104 
	 [18176 18432 17408 17664]
1136 1152 1104 1120 
	 [18176 18432 17664 17920]
1136 1152 1120 1136 
	 [18176 18432 17920 18176]
1136 1152 1136 1152 
	 [18176 18432 18176 18432]
1136 1152 1152 1168 
	 [18176 18432 18432 18688]
1136 1152 1168 1184 
	 [18176 18432 18688 18944]
1136 1152 1184 1200 
	 [18176 18432 18944 19200]
1136 1152 1200 1216 
	 [18176 18432 19200 19456]
1136 1152 1216 1232 
	 [18176 184

1184 1200 1600 1616 
	 [18944 19200 25600 25856]
1184 1200 1616 1632 
	 [18944 19200 25856 26112]
1184 1200 1632 1648 
	 [18944 19200 26112 26368]
1184 1200 1648 1664 
	 [18944 19200 26368 26624]
1184 1200 1664 1680 
	 [18944 19200 26624 26880]
1184 1200 1680 1696 
	 [18944 19200 26880 27136]
1184 1200 1696 1712 
	 [18944 19200 27136 27392]
1184 1200 1712 1728 
	 [18944 19200 27392 27648]
1184 1200 1728 1744 
	 [18944 19200 27648 27904]
1184 1200 1744 1760 
	 [18944 19200 27904 28160]
1184 1200 1760 1776 
	 [18944 19200 28160 28416]
1184 1200 1776 1792 
	 [18944 19200 28416 28672]
1184 1200 1792 1808 
	 [18944 19200 28672 28928]
1184 1200 1808 1824 
	 [18944 19200 28928 29184]
1184 1200 1824 1840 
	 [18944 19200 29184 29440]
1184 1200 1840 1856 
	 [18944 19200 29440 29696]
1184 1200 1856 1872 
	 [18944 19200 29696 29952]
1184 1200 1872 1888 
	 [18944 19200 29952 30208]
1184 1200 1888 1904 
	 [18944 19200 30208 30464]
1184 1200 1904 1920 
	 [18944 19200 30464 30720]
1184 1200 1920 1936 

1248 1264 1392 1408 
	 [19968 20224 22272 22528]
1248 1264 1408 1424 
	 [19968 20224 22528 22784]
1248 1264 1424 1440 
	 [19968 20224 22784 23040]
1248 1264 1440 1456 
	 [19968 20224 23040 23296]
1248 1264 1456 1472 
	 [19968 20224 23296 23552]
1248 1264 1472 1488 
	 [19968 20224 23552 23808]
1248 1264 1488 1504 
	 [19968 20224 23808 24064]
1248 1264 1504 1520 
	 [19968 20224 24064 24320]
1248 1264 1520 1536 
	 [19968 20224 24320 24576]
1248 1264 1536 1552 
	 [19968 20224 24576 24832]
1248 1264 1552 1568 
	 [19968 20224 24832 25088]
1248 1264 1568 1584 
	 [19968 20224 25088 25344]
1248 1264 1584 1600 
	 [19968 20224 25344 25600]
1248 1264 1600 1616 
	 [19968 20224 25600 25856]
1248 1264 1616 1632 
	 [19968 20224 25856 26112]
1248 1264 1632 1648 
	 [19968 20224 26112 26368]
1248 1264 1648 1664 
	 [19968 20224 26368 26624]
1248 1264 1664 1680 
	 [19968 20224 26624 26880]
1248 1264 1680 1696 
	 [19968 20224 26880 27136]
1248 1264 1696 1712 
	 [19968 20224 27136 27392]
1248 1264 1712 1728 

	 [20736 20992 26112 26368]
1296 1312 1648 1664 
	 [20736 20992 26368 26624]
1296 1312 1664 1680 
	 [20736 20992 26624 26880]
1296 1312 1680 1696 
	 [20736 20992 26880 27136]
1296 1312 1696 1712 
	 [20736 20992 27136 27392]
1296 1312 1712 1728 
	 [20736 20992 27392 27648]
1296 1312 1728 1744 
	 [20736 20992 27648 27904]
1296 1312 1744 1760 
	 [20736 20992 27904 28160]
1296 1312 1760 1776 
	 [20736 20992 28160 28416]
1296 1312 1776 1792 
	 [20736 20992 28416 28672]
1296 1312 1792 1808 
	 [20736 20992 28672 28928]
1296 1312 1808 1824 
	 [20736 20992 28928 29184]
1296 1312 1824 1840 
	 [20736 20992 29184 29440]
1296 1312 1840 1856 
	 [20736 20992 29440 29696]
1296 1312 1856 1872 
	 [20736 20992 29696 29952]
1296 1312 1872 1888 
	 [20736 20992 29952 30208]
1296 1312 1888 1904 
	 [20736 20992 30208 30464]
1296 1312 1904 1920 
	 [20736 20992 30464 30720]
1296 1312 1920 1936 
	 [20736 20992 30720 30976]
1296 1312 1936 1952 
	 [20736 20992 30976 31232]
1296 1312 1952 1968 
	 [20736 20992 31232

1360 1376 400 416 
	 [21760 22016  6400  6656]
1360 1376 416 432 
	 [21760 22016  6656  6912]
1360 1376 432 448 
	 [21760 22016  6912  7168]
1360 1376 448 464 
	 [21760 22016  7168  7424]
1360 1376 464 480 
	 [21760 22016  7424  7680]
1360 1376 480 496 
	 [21760 22016  7680  7936]
1360 1376 496 512 
	 [21760 22016  7936  8192]
1360 1376 512 528 
	 [21760 22016  8192  8448]
1360 1376 528 544 
	 [21760 22016  8448  8704]
1360 1376 544 560 
	 [21760 22016  8704  8960]
1360 1376 560 576 
	 [21760 22016  8960  9216]
1360 1376 576 592 
	 [21760 22016  9216  9472]
1360 1376 592 608 
	 [21760 22016  9472  9728]
1360 1376 608 624 
	 [21760 22016  9728  9984]
1360 1376 624 640 
	 [21760 22016  9984 10240]
1360 1376 640 656 
	 [21760 22016 10240 10496]
1360 1376 656 672 
	 [21760 22016 10496 10752]
1360 1376 672 688 
	 [21760 22016 10752 11008]
1360 1376 688 704 
	 [21760 22016 11008 11264]
1360 1376 704 720 
	 [21760 22016 11264 11520]
1360 1376 720 736 
	 [21760 22016 11520 11776]
1360 1376 736

1424 1440 208 224 
	 [22784 23040  3328  3584]
1424 1440 224 240 
	 [22784 23040  3584  3840]
1424 1440 240 256 
	 [22784 23040  3840  4096]
1424 1440 256 272 
	 [22784 23040  4096  4352]
1424 1440 272 288 
	 [22784 23040  4352  4608]
1424 1440 288 304 
	 [22784 23040  4608  4864]
1424 1440 304 320 
	 [22784 23040  4864  5120]
1424 1440 320 336 
	 [22784 23040  5120  5376]
1424 1440 336 352 
	 [22784 23040  5376  5632]
1424 1440 352 368 
	 [22784 23040  5632  5888]
1424 1440 368 384 
	 [22784 23040  5888  6144]
1424 1440 384 400 
	 [22784 23040  6144  6400]
1424 1440 400 416 
	 [22784 23040  6400  6656]
1424 1440 416 432 
	 [22784 23040  6656  6912]
1424 1440 432 448 
	 [22784 23040  6912  7168]
1424 1440 448 464 
	 [22784 23040  7168  7424]
1424 1440 464 480 
	 [22784 23040  7424  7680]
1424 1440 480 496 
	 [22784 23040  7680  7936]
1424 1440 496 512 
	 [22784 23040  7936  8192]
1424 1440 512 528 
	 [22784 23040  8192  8448]
1424 1440 528 544 
	 [22784 23040  8448  8704]
1424 1440 544

1488 1504 0 16 
	 [23808 24064     0   256]
1488 1504 16 32 
	 [23808 24064   256   512]
1488 1504 32 48 
	 [23808 24064   512   768]
1488 1504 48 64 
	 [23808 24064   768  1024]
1488 1504 64 80 
	 [23808 24064  1024  1280]
1488 1504 80 96 
	 [23808 24064  1280  1536]
1488 1504 96 112 
	 [23808 24064  1536  1792]
1488 1504 112 128 
	 [23808 24064  1792  2048]
1488 1504 128 144 
	 [23808 24064  2048  2304]
1488 1504 144 160 
	 [23808 24064  2304  2560]
1488 1504 160 176 
	 [23808 24064  2560  2816]
1488 1504 176 192 
	 [23808 24064  2816  3072]
1488 1504 192 208 
	 [23808 24064  3072  3328]
1488 1504 208 224 
	 [23808 24064  3328  3584]
1488 1504 224 240 
	 [23808 24064  3584  3840]
1488 1504 240 256 
	 [23808 24064  3840  4096]
1488 1504 256 272 
	 [23808 24064  4096  4352]
1488 1504 272 288 
	 [23808 24064  4352  4608]
1488 1504 288 304 
	 [23808 24064  4608  4864]
1488 1504 304 320 
	 [23808 24064  4864  5120]
1488 1504 320 336 
	 [23808 24064  5120  5376]
1488 1504 336 352 
	 [23808

1536 1552 1216 1232 
	 [24576 24832 19456 19712]
1536 1552 1232 1248 
	 [24576 24832 19712 19968]
1536 1552 1248 1264 
	 [24576 24832 19968 20224]
1536 1552 1264 1280 
	 [24576 24832 20224 20480]
1536 1552 1280 1296 
	 [24576 24832 20480 20736]
1536 1552 1296 1312 
	 [24576 24832 20736 20992]
1536 1552 1312 1328 
	 [24576 24832 20992 21248]
1536 1552 1328 1344 
	 [24576 24832 21248 21504]
1536 1552 1344 1360 
	 [24576 24832 21504 21760]
1536 1552 1360 1376 
	 [24576 24832 21760 22016]
1536 1552 1376 1392 
	 [24576 24832 22016 22272]
1536 1552 1392 1408 
	 [24576 24832 22272 22528]
1536 1552 1408 1424 
	 [24576 24832 22528 22784]
1536 1552 1424 1440 
	 [24576 24832 22784 23040]
1536 1552 1440 1456 
	 [24576 24832 23040 23296]
1536 1552 1456 1472 
	 [24576 24832 23296 23552]
1536 1552 1472 1488 
	 [24576 24832 23552 23808]
1536 1552 1488 1504 
	 [24576 24832 23808 24064]
1536 1552 1504 1520 
	 [24576 24832 24064 24320]
1536 1552 1520 1536 
	 [24576 24832 24320 24576]
1536 1552 1536 1552 

	 [25600 25856     0   256]
1600 1616 16 32 
	 [25600 25856   256   512]
1600 1616 32 48 
	 [25600 25856   512   768]
1600 1616 48 64 
	 [25600 25856   768  1024]
1600 1616 64 80 
	 [25600 25856  1024  1280]
1600 1616 80 96 
	 [25600 25856  1280  1536]
1600 1616 96 112 
	 [25600 25856  1536  1792]
1600 1616 112 128 
	 [25600 25856  1792  2048]
1600 1616 128 144 
	 [25600 25856  2048  2304]
1600 1616 144 160 
	 [25600 25856  2304  2560]
1600 1616 160 176 
	 [25600 25856  2560  2816]
1600 1616 176 192 
	 [25600 25856  2816  3072]
1600 1616 192 208 
	 [25600 25856  3072  3328]
1600 1616 208 224 
	 [25600 25856  3328  3584]
1600 1616 224 240 
	 [25600 25856  3584  3840]
1600 1616 240 256 
	 [25600 25856  3840  4096]
1600 1616 256 272 
	 [25600 25856  4096  4352]
1600 1616 272 288 
	 [25600 25856  4352  4608]
1600 1616 288 304 
	 [25600 25856  4608  4864]
1600 1616 304 320 
	 [25600 25856  4864  5120]
1600 1616 320 336 
	 [25600 25856  5120  5376]
1600 1616 336 352 
	 [25600 25856  5376  56

1648 1664 864 880 
	 [26368 26624 13824 14080]
1648 1664 880 896 
	 [26368 26624 14080 14336]
1648 1664 896 912 
	 [26368 26624 14336 14592]
1648 1664 912 928 
	 [26368 26624 14592 14848]
1648 1664 928 944 
	 [26368 26624 14848 15104]
1648 1664 944 960 
	 [26368 26624 15104 15360]
1648 1664 960 976 
	 [26368 26624 15360 15616]
1648 1664 976 992 
	 [26368 26624 15616 15872]
1648 1664 992 1008 
	 [26368 26624 15872 16128]
1648 1664 1008 1024 
	 [26368 26624 16128 16384]
1648 1664 1024 1040 
	 [26368 26624 16384 16640]
1648 1664 1040 1056 
	 [26368 26624 16640 16896]
1648 1664 1056 1072 
	 [26368 26624 16896 17152]
1648 1664 1072 1088 
	 [26368 26624 17152 17408]
1648 1664 1088 1104 
	 [26368 26624 17408 17664]
1648 1664 1104 1120 
	 [26368 26624 17664 17920]
1648 1664 1120 1136 
	 [26368 26624 17920 18176]
1648 1664 1136 1152 
	 [26368 26624 18176 18432]
1648 1664 1152 1168 
	 [26368 26624 18432 18688]
1648 1664 1168 1184 
	 [26368 26624 18688 18944]
1648 1664 1184 1200 
	 [26368 26624 1

	 [27136 27392 22016 22272]
1696 1712 1392 1408 
	 [27136 27392 22272 22528]
1696 1712 1408 1424 
	 [27136 27392 22528 22784]
1696 1712 1424 1440 
	 [27136 27392 22784 23040]
1696 1712 1440 1456 
	 [27136 27392 23040 23296]
1696 1712 1456 1472 
	 [27136 27392 23296 23552]
1696 1712 1472 1488 
	 [27136 27392 23552 23808]
1696 1712 1488 1504 
	 [27136 27392 23808 24064]
1696 1712 1504 1520 
	 [27136 27392 24064 24320]
1696 1712 1520 1536 
	 [27136 27392 24320 24576]
1696 1712 1536 1552 
	 [27136 27392 24576 24832]
1696 1712 1552 1568 
	 [27136 27392 24832 25088]
1696 1712 1568 1584 
	 [27136 27392 25088 25344]
1696 1712 1584 1600 
	 [27136 27392 25344 25600]
1696 1712 1600 1616 
	 [27136 27392 25600 25856]
1696 1712 1616 1632 
	 [27136 27392 25856 26112]
1696 1712 1632 1648 
	 [27136 27392 26112 26368]
1696 1712 1648 1664 
	 [27136 27392 26368 26624]
1696 1712 1664 1680 
	 [27136 27392 26624 26880]
1696 1712 1680 1696 
	 [27136 27392 26880 27136]
1696 1712 1696 1712 
	 [27136 27392 27136

	 [28160 28416 11776 12032]
1760 1776 752 768 
	 [28160 28416 12032 12288]
1760 1776 768 784 
	 [28160 28416 12288 12544]
1760 1776 784 800 
	 [28160 28416 12544 12800]
1760 1776 800 816 
	 [28160 28416 12800 13056]
1760 1776 816 832 
	 [28160 28416 13056 13312]
1760 1776 832 848 
	 [28160 28416 13312 13568]
1760 1776 848 864 
	 [28160 28416 13568 13824]
1760 1776 864 880 
	 [28160 28416 13824 14080]
1760 1776 880 896 
	 [28160 28416 14080 14336]
1760 1776 896 912 
	 [28160 28416 14336 14592]
1760 1776 912 928 
	 [28160 28416 14592 14848]
1760 1776 928 944 
	 [28160 28416 14848 15104]
1760 1776 944 960 
	 [28160 28416 15104 15360]
1760 1776 960 976 
	 [28160 28416 15360 15616]
1760 1776 976 992 
	 [28160 28416 15616 15872]
1760 1776 992 1008 
	 [28160 28416 15872 16128]
1760 1776 1008 1024 
	 [28160 28416 16128 16384]
1760 1776 1024 1040 
	 [28160 28416 16384 16640]
1760 1776 1040 1056 
	 [28160 28416 16640 16896]
1760 1776 1056 1072 
	 [28160 28416 16896 17152]
1760 1776 1072 1088 
	 

1808 1824 384 400 
	 [28928 29184  6144  6400]
1808 1824 400 416 
	 [28928 29184  6400  6656]
1808 1824 416 432 
	 [28928 29184  6656  6912]
1808 1824 432 448 
	 [28928 29184  6912  7168]
1808 1824 448 464 
	 [28928 29184  7168  7424]
1808 1824 464 480 
	 [28928 29184  7424  7680]
1808 1824 480 496 
	 [28928 29184  7680  7936]
1808 1824 496 512 
	 [28928 29184  7936  8192]
1808 1824 512 528 
	 [28928 29184  8192  8448]
1808 1824 528 544 
	 [28928 29184  8448  8704]
1808 1824 544 560 
	 [28928 29184  8704  8960]
1808 1824 560 576 
	 [28928 29184  8960  9216]
1808 1824 576 592 
	 [28928 29184  9216  9472]
1808 1824 592 608 
	 [28928 29184  9472  9728]
1808 1824 608 624 
	 [28928 29184  9728  9984]
1808 1824 624 640 
	 [28928 29184  9984 10240]
1808 1824 640 656 
	 [28928 29184 10240 10496]
1808 1824 656 672 
	 [28928 29184 10496 10752]
1808 1824 672 688 
	 [28928 29184 10752 11008]
1808 1824 688 704 
	 [28928 29184 11008 11264]
1808 1824 704 720 
	 [28928 29184 11264 11520]
1808 1824 720

1856 1872 896 912 
	 [29696 29952 14336 14592]
1856 1872 912 928 
	 [29696 29952 14592 14848]
1856 1872 928 944 
	 [29696 29952 14848 15104]
1856 1872 944 960 
	 [29696 29952 15104 15360]
1856 1872 960 976 
	 [29696 29952 15360 15616]
1856 1872 976 992 
	 [29696 29952 15616 15872]
1856 1872 992 1008 
	 [29696 29952 15872 16128]
1856 1872 1008 1024 
	 [29696 29952 16128 16384]
1856 1872 1024 1040 
	 [29696 29952 16384 16640]
1856 1872 1040 1056 
	 [29696 29952 16640 16896]
1856 1872 1056 1072 
	 [29696 29952 16896 17152]
1856 1872 1072 1088 
	 [29696 29952 17152 17408]
1856 1872 1088 1104 
	 [29696 29952 17408 17664]
1856 1872 1104 1120 
	 [29696 29952 17664 17920]
1856 1872 1120 1136 
	 [29696 29952 17920 18176]
1856 1872 1136 1152 
	 [29696 29952 18176 18432]
1856 1872 1152 1168 
	 [29696 29952 18432 18688]
1856 1872 1168 1184 
	 [29696 29952 18688 18944]
1856 1872 1184 1200 
	 [29696 29952 18944 19200]
1856 1872 1200 1216 
	 [29696 29952 19200 19456]
1856 1872 1216 1232 
	 [29696 299

1904 1920 1424 1440 
	 [30464 30720 22784 23040]
1904 1920 1440 1456 
	 [30464 30720 23040 23296]
1904 1920 1456 1472 
	 [30464 30720 23296 23552]
1904 1920 1472 1488 
	 [30464 30720 23552 23808]
1904 1920 1488 1504 
	 [30464 30720 23808 24064]
1904 1920 1504 1520 
	 [30464 30720 24064 24320]
1904 1920 1520 1536 
	 [30464 30720 24320 24576]
1904 1920 1536 1552 
	 [30464 30720 24576 24832]
1904 1920 1552 1568 
	 [30464 30720 24832 25088]
1904 1920 1568 1584 
	 [30464 30720 25088 25344]
1904 1920 1584 1600 
	 [30464 30720 25344 25600]
1904 1920 1600 1616 
	 [30464 30720 25600 25856]
1904 1920 1616 1632 
	 [30464 30720 25856 26112]
1904 1920 1632 1648 
	 [30464 30720 26112 26368]
1904 1920 1648 1664 
	 [30464 30720 26368 26624]
1904 1920 1664 1680 
	 [30464 30720 26624 26880]
1904 1920 1680 1696 
	 [30464 30720 26880 27136]
1904 1920 1696 1712 
	 [30464 30720 27136 27392]
1904 1920 1712 1728 
	 [30464 30720 27392 27648]
1904 1920 1728 1744 
	 [30464 30720 27648 27904]
1904 1920 1744 1760 

1952 1968 1568 1584 
	 [31232 31488 25088 25344]
1952 1968 1584 1600 
	 [31232 31488 25344 25600]
1952 1968 1600 1616 
	 [31232 31488 25600 25856]
1952 1968 1616 1632 
	 [31232 31488 25856 26112]
1952 1968 1632 1648 
	 [31232 31488 26112 26368]
1952 1968 1648 1664 
	 [31232 31488 26368 26624]
1952 1968 1664 1680 
	 [31232 31488 26624 26880]
1952 1968 1680 1696 
	 [31232 31488 26880 27136]
1952 1968 1696 1712 
	 [31232 31488 27136 27392]
1952 1968 1712 1728 
	 [31232 31488 27392 27648]
1952 1968 1728 1744 
	 [31232 31488 27648 27904]
1952 1968 1744 1760 
	 [31232 31488 27904 28160]
1952 1968 1760 1776 
	 [31232 31488 28160 28416]
1952 1968 1776 1792 
	 [31232 31488 28416 28672]
1952 1968 1792 1808 
	 [31232 31488 28672 28928]
1952 1968 1808 1824 
	 [31232 31488 28928 29184]
1952 1968 1824 1840 
	 [31232 31488 29184 29440]
1952 1968 1840 1856 
	 [31232 31488 29440 29696]
1952 1968 1856 1872 
	 [31232 31488 29696 29952]
1952 1968 1872 1888 
	 [31232 31488 29952 30208]
1952 1968 1888 1904 

2000 2016 1136 1152 
	 [32000 32256 18176 18432]
2000 2016 1152 1168 
	 [32000 32256 18432 18688]
2000 2016 1168 1184 
	 [32000 32256 18688 18944]
2000 2016 1184 1200 
	 [32000 32256 18944 19200]
2000 2016 1200 1216 
	 [32000 32256 19200 19456]
2000 2016 1216 1232 
	 [32000 32256 19456 19712]
2000 2016 1232 1248 
	 [32000 32256 19712 19968]
2000 2016 1248 1264 
	 [32000 32256 19968 20224]
2000 2016 1264 1280 
	 [32000 32256 20224 20480]
2000 2016 1280 1296 
	 [32000 32256 20480 20736]
2000 2016 1296 1312 
	 [32000 32256 20736 20992]
2000 2016 1312 1328 
	 [32000 32256 20992 21248]
2000 2016 1328 1344 
	 [32000 32256 21248 21504]
2000 2016 1344 1360 
	 [32000 32256 21504 21760]
2000 2016 1360 1376 
	 [32000 32256 21760 22016]
2000 2016 1376 1392 
	 [32000 32256 22016 22272]
2000 2016 1392 1408 
	 [32000 32256 22272 22528]
2000 2016 1408 1424 
	 [32000 32256 22528 22784]
2000 2016 1424 1440 
	 [32000 32256 22784 23040]
2000 2016 1440 1456 
	 [32000 32256 23040 23296]
2000 2016 1456 1472 

2048 2064 320 336 
	 [32768 33024  5120  5376]
2048 2064 336 352 
	 [32768 33024  5376  5632]
2048 2064 352 368 
	 [32768 33024  5632  5888]
2048 2064 368 384 
	 [32768 33024  5888  6144]
2048 2064 384 400 
	 [32768 33024  6144  6400]
2048 2064 400 416 
	 [32768 33024  6400  6656]
2048 2064 416 432 
	 [32768 33024  6656  6912]
2048 2064 432 448 
	 [32768 33024  6912  7168]
2048 2064 448 464 
	 [32768 33024  7168  7424]
2048 2064 464 480 
	 [32768 33024  7424  7680]
2048 2064 480 496 
	 [32768 33024  7680  7936]
2048 2064 496 512 
	 [32768 33024  7936  8192]
2048 2064 512 528 
	 [32768 33024  8192  8448]
2048 2064 528 544 
	 [32768 33024  8448  8704]
2048 2064 544 560 
	 [32768 33024  8704  8960]
2048 2064 560 576 
	 [32768 33024  8960  9216]
2048 2064 576 592 
	 [32768 33024  9216  9472]
2048 2064 592 608 
	 [32768 33024  9472  9728]
2048 2064 608 624 
	 [32768 33024  9728  9984]
2048 2064 624 640 
	 [32768 33024  9984 10240]
2048 2064 640 656 
	 [32768 33024 10240 10496]
2048 2064 656

	 [33536 33792  4096  4352]
2096 2112 272 288 
	 [33536 33792  4352  4608]
2096 2112 288 304 
	 [33536 33792  4608  4864]
2096 2112 304 320 
	 [33536 33792  4864  5120]
2096 2112 320 336 
	 [33536 33792  5120  5376]
2096 2112 336 352 
	 [33536 33792  5376  5632]
2096 2112 352 368 
	 [33536 33792  5632  5888]
2096 2112 368 384 
	 [33536 33792  5888  6144]
2096 2112 384 400 
	 [33536 33792  6144  6400]
2096 2112 400 416 
	 [33536 33792  6400  6656]
2096 2112 416 432 
	 [33536 33792  6656  6912]
2096 2112 432 448 
	 [33536 33792  6912  7168]
2096 2112 448 464 
	 [33536 33792  7168  7424]
2096 2112 464 480 
	 [33536 33792  7424  7680]
2096 2112 480 496 
	 [33536 33792  7680  7936]
2096 2112 496 512 
	 [33536 33792  7936  8192]
2096 2112 512 528 
	 [33536 33792  8192  8448]
2096 2112 528 544 
	 [33536 33792  8448  8704]
2096 2112 544 560 
	 [33536 33792  8704  8960]
2096 2112 560 576 
	 [33536 33792  8960  9216]
2096 2112 576 592 
	 [33536 33792  9216  9472]
2096 2112 592 608 
	 [33536 3379

2144 2160 32 48 
	 [34304 34560   512   768]
2144 2160 48 64 
	 [34304 34560   768  1024]
2144 2160 64 80 
	 [34304 34560  1024  1280]
2144 2160 80 96 
	 [34304 34560  1280  1536]
2144 2160 96 112 
	 [34304 34560  1536  1792]
2144 2160 112 128 
	 [34304 34560  1792  2048]
2144 2160 128 144 
	 [34304 34560  2048  2304]
2144 2160 144 160 
	 [34304 34560  2304  2560]
2144 2160 160 176 
	 [34304 34560  2560  2816]
2144 2160 176 192 
	 [34304 34560  2816  3072]
2144 2160 192 208 
	 [34304 34560  3072  3328]
2144 2160 208 224 
	 [34304 34560  3328  3584]
2144 2160 224 240 
	 [34304 34560  3584  3840]
2144 2160 240 256 
	 [34304 34560  3840  4096]
2144 2160 256 272 
	 [34304 34560  4096  4352]
2144 2160 272 288 
	 [34304 34560  4352  4608]
2144 2160 288 304 
	 [34304 34560  4608  4864]
2144 2160 304 320 
	 [34304 34560  4864  5120]
2144 2160 320 336 
	 [34304 34560  5120  5376]
2144 2160 336 352 
	 [34304 34560  5376  5632]
2144 2160 352 368 
	 [34304 34560  5632  5888]
2144 2160 368 384 
	 [

2176 2192 1264 1280 
	 [34816 35072 20224 20480]
2176 2192 1280 1296 
	 [34816 35072 20480 20736]
2176 2192 1296 1312 
	 [34816 35072 20736 20992]
2176 2192 1312 1328 
	 [34816 35072 20992 21248]
2176 2192 1328 1344 
	 [34816 35072 21248 21504]
2176 2192 1344 1360 
	 [34816 35072 21504 21760]
2176 2192 1360 1376 
	 [34816 35072 21760 22016]
2176 2192 1376 1392 
	 [34816 35072 22016 22272]
2176 2192 1392 1408 
	 [34816 35072 22272 22528]
2176 2192 1408 1424 
	 [34816 35072 22528 22784]
2176 2192 1424 1440 
	 [34816 35072 22784 23040]
2176 2192 1440 1456 
	 [34816 35072 23040 23296]
2176 2192 1456 1472 
	 [34816 35072 23296 23552]
2176 2192 1472 1488 
	 [34816 35072 23552 23808]
2176 2192 1488 1504 
	 [34816 35072 23808 24064]
2176 2192 1504 1520 
	 [34816 35072 24064 24320]
2176 2192 1520 1536 
	 [34816 35072 24320 24576]
2176 2192 1536 1552 
	 [34816 35072 24576 24832]
2176 2192 1552 1568 
	 [34816 35072 24832 25088]
2176 2192 1568 1584 
	 [34816 35072 25088 25344]
2176 2192 1584 1600 

2240 2256 1072 1088 
	 [35840 36096 17152 17408]
2240 2256 1088 1104 
	 [35840 36096 17408 17664]
2240 2256 1104 1120 
	 [35840 36096 17664 17920]
2240 2256 1120 1136 
	 [35840 36096 17920 18176]
2240 2256 1136 1152 
	 [35840 36096 18176 18432]
2240 2256 1152 1168 
	 [35840 36096 18432 18688]
2240 2256 1168 1184 
	 [35840 36096 18688 18944]
2240 2256 1184 1200 
	 [35840 36096 18944 19200]
2240 2256 1200 1216 
	 [35840 36096 19200 19456]
2240 2256 1216 1232 
	 [35840 36096 19456 19712]
2240 2256 1232 1248 
	 [35840 36096 19712 19968]
2240 2256 1248 1264 
	 [35840 36096 19968 20224]
2240 2256 1264 1280 
	 [35840 36096 20224 20480]
2240 2256 1280 1296 
	 [35840 36096 20480 20736]
2240 2256 1296 1312 
	 [35840 36096 20736 20992]
2240 2256 1312 1328 
	 [35840 36096 20992 21248]
2240 2256 1328 1344 
	 [35840 36096 21248 21504]
2240 2256 1344 1360 
	 [35840 36096 21504 21760]
2240 2256 1360 1376 
	 [35840 36096 21760 22016]
2240 2256 1376 1392 
	 [35840 36096 22016 22272]
2240 2256 1392 1408 

	 [36608 36864 25344 25600]
2288 2304 1600 1616 
	 [36608 36864 25600 25856]
2288 2304 1616 1632 
	 [36608 36864 25856 26112]
2288 2304 1632 1648 
	 [36608 36864 26112 26368]
2288 2304 1648 1664 
	 [36608 36864 26368 26624]
2288 2304 1664 1680 
	 [36608 36864 26624 26880]
2288 2304 1680 1696 
	 [36608 36864 26880 27136]
2288 2304 1696 1712 
	 [36608 36864 27136 27392]
2288 2304 1712 1728 
	 [36608 36864 27392 27648]
2288 2304 1728 1744 
	 [36608 36864 27648 27904]
2288 2304 1744 1760 
	 [36608 36864 27904 28160]
2288 2304 1760 1776 
	 [36608 36864 28160 28416]
2288 2304 1776 1792 
	 [36608 36864 28416 28672]
2288 2304 1792 1808 
	 [36608 36864 28672 28928]
2288 2304 1808 1824 
	 [36608 36864 28928 29184]
2288 2304 1824 1840 
	 [36608 36864 29184 29440]
2288 2304 1840 1856 
	 [36608 36864 29440 29696]
2288 2304 1856 1872 
	 [36608 36864 29696 29952]
2288 2304 1872 1888 
	 [36608 36864 29952 30208]
2288 2304 1888 1904 
	 [36608 36864 30208 30464]
2288 2304 1904 1920 
	 [36608 36864 30464

2352 2368 64 80 
	 [37632 37888  1024  1280]
2352 2368 80 96 
	 [37632 37888  1280  1536]
2352 2368 96 112 
	 [37632 37888  1536  1792]
2352 2368 112 128 
	 [37632 37888  1792  2048]
2352 2368 128 144 
	 [37632 37888  2048  2304]
2352 2368 144 160 
	 [37632 37888  2304  2560]
2352 2368 160 176 
	 [37632 37888  2560  2816]
2352 2368 176 192 
	 [37632 37888  2816  3072]
2352 2368 192 208 
	 [37632 37888  3072  3328]
2352 2368 208 224 
	 [37632 37888  3328  3584]
2352 2368 224 240 
	 [37632 37888  3584  3840]
2352 2368 240 256 
	 [37632 37888  3840  4096]
2352 2368 256 272 
	 [37632 37888  4096  4352]
2352 2368 272 288 
	 [37632 37888  4352  4608]
2352 2368 288 304 
	 [37632 37888  4608  4864]
2352 2368 304 320 
	 [37632 37888  4864  5120]
2352 2368 320 336 
	 [37632 37888  5120  5376]
2352 2368 336 352 
	 [37632 37888  5376  5632]
2352 2368 352 368 
	 [37632 37888  5632  5888]
2352 2368 368 384 
	 [37632 37888  5888  6144]
2352 2368 384 400 
	 [37632 37888  6144  6400]
2352 2368 400 416 

	 [38400 38656  4096  4352]
2400 2416 272 288 
	 [38400 38656  4352  4608]
2400 2416 288 304 
	 [38400 38656  4608  4864]
2400 2416 304 320 
	 [38400 38656  4864  5120]
2400 2416 320 336 
	 [38400 38656  5120  5376]
2400 2416 336 352 
	 [38400 38656  5376  5632]
2400 2416 352 368 
	 [38400 38656  5632  5888]
2400 2416 368 384 
	 [38400 38656  5888  6144]
2400 2416 384 400 
	 [38400 38656  6144  6400]
2400 2416 400 416 
	 [38400 38656  6400  6656]
2400 2416 416 432 
	 [38400 38656  6656  6912]
2400 2416 432 448 
	 [38400 38656  6912  7168]
2400 2416 448 464 
	 [38400 38656  7168  7424]
2400 2416 464 480 
	 [38400 38656  7424  7680]
2400 2416 480 496 
	 [38400 38656  7680  7936]
2400 2416 496 512 
	 [38400 38656  7936  8192]
2400 2416 512 528 
	 [38400 38656  8192  8448]
2400 2416 528 544 
	 [38400 38656  8448  8704]
2400 2416 544 560 
	 [38400 38656  8704  8960]
2400 2416 560 576 
	 [38400 38656  8960  9216]
2400 2416 576 592 
	 [38400 38656  9216  9472]
2400 2416 592 608 
	 [38400 3865

2448 2464 1104 1120 
	 [39168 39424 17664 17920]
2448 2464 1120 1136 
	 [39168 39424 17920 18176]
2448 2464 1136 1152 
	 [39168 39424 18176 18432]
2448 2464 1152 1168 
	 [39168 39424 18432 18688]
2448 2464 1168 1184 
	 [39168 39424 18688 18944]
2448 2464 1184 1200 
	 [39168 39424 18944 19200]
2448 2464 1200 1216 
	 [39168 39424 19200 19456]
2448 2464 1216 1232 
	 [39168 39424 19456 19712]
2448 2464 1232 1248 
	 [39168 39424 19712 19968]
2448 2464 1248 1264 
	 [39168 39424 19968 20224]
2448 2464 1264 1280 
	 [39168 39424 20224 20480]
2448 2464 1280 1296 
	 [39168 39424 20480 20736]
2448 2464 1296 1312 
	 [39168 39424 20736 20992]
2448 2464 1312 1328 
	 [39168 39424 20992 21248]
2448 2464 1328 1344 
	 [39168 39424 21248 21504]
2448 2464 1344 1360 
	 [39168 39424 21504 21760]
2448 2464 1360 1376 
	 [39168 39424 21760 22016]
2448 2464 1376 1392 
	 [39168 39424 22016 22272]
2448 2464 1392 1408 
	 [39168 39424 22272 22528]
2448 2464 1408 1424 
	 [39168 39424 22528 22784]
2448 2464 1424 1440 

	 [39936 40192  4608  4864]
2496 2512 304 320 
	 [39936 40192  4864  5120]
2496 2512 320 336 
	 [39936 40192  5120  5376]
2496 2512 336 352 
	 [39936 40192  5376  5632]
2496 2512 352 368 
	 [39936 40192  5632  5888]
2496 2512 368 384 
	 [39936 40192  5888  6144]
2496 2512 384 400 
	 [39936 40192  6144  6400]
2496 2512 400 416 
	 [39936 40192  6400  6656]
2496 2512 416 432 
	 [39936 40192  6656  6912]
2496 2512 432 448 
	 [39936 40192  6912  7168]
2496 2512 448 464 
	 [39936 40192  7168  7424]
2496 2512 464 480 
	 [39936 40192  7424  7680]
2496 2512 480 496 
	 [39936 40192  7680  7936]
2496 2512 496 512 
	 [39936 40192  7936  8192]
2496 2512 512 528 
	 [39936 40192  8192  8448]
2496 2512 528 544 
	 [39936 40192  8448  8704]
2496 2512 544 560 
	 [39936 40192  8704  8960]
2496 2512 560 576 
	 [39936 40192  8960  9216]
2496 2512 576 592 
	 [39936 40192  9216  9472]
2496 2512 592 608 
	 [39936 40192  9472  9728]
2496 2512 608 624 
	 [39936 40192  9728  9984]
2496 2512 624 640 
	 [39936 4019

2544 2560 816 832 
	 [40704 40960 13056 13312]
2544 2560 832 848 
	 [40704 40960 13312 13568]
2544 2560 848 864 
	 [40704 40960 13568 13824]
2544 2560 864 880 
	 [40704 40960 13824 14080]
2544 2560 880 896 
	 [40704 40960 14080 14336]
2544 2560 896 912 
	 [40704 40960 14336 14592]
2544 2560 912 928 
	 [40704 40960 14592 14848]
2544 2560 928 944 
	 [40704 40960 14848 15104]
2544 2560 944 960 
	 [40704 40960 15104 15360]
2544 2560 960 976 
	 [40704 40960 15360 15616]
2544 2560 976 992 
	 [40704 40960 15616 15872]
2544 2560 992 1008 
	 [40704 40960 15872 16128]
2544 2560 1008 1024 
	 [40704 40960 16128 16384]
2544 2560 1024 1040 
	 [40704 40960 16384 16640]
2544 2560 1040 1056 
	 [40704 40960 16640 16896]
2544 2560 1056 1072 
	 [40704 40960 16896 17152]
2544 2560 1072 1088 
	 [40704 40960 17152 17408]
2544 2560 1088 1104 
	 [40704 40960 17408 17664]
2544 2560 1104 1120 
	 [40704 40960 17664 17920]
2544 2560 1120 1136 
	 [40704 40960 17920 18176]
2544 2560 1136 1152 
	 [40704 40960 18176 1

2608 2624 624 640 
	 [41728 41984  9984 10240]
2608 2624 640 656 
	 [41728 41984 10240 10496]
2608 2624 656 672 
	 [41728 41984 10496 10752]
2608 2624 672 688 
	 [41728 41984 10752 11008]
2608 2624 688 704 
	 [41728 41984 11008 11264]
2608 2624 704 720 
	 [41728 41984 11264 11520]
2608 2624 720 736 
	 [41728 41984 11520 11776]
2608 2624 736 752 
	 [41728 41984 11776 12032]
2608 2624 752 768 
	 [41728 41984 12032 12288]
2608 2624 768 784 
	 [41728 41984 12288 12544]
2608 2624 784 800 
	 [41728 41984 12544 12800]
2608 2624 800 816 
	 [41728 41984 12800 13056]
2608 2624 816 832 
	 [41728 41984 13056 13312]
2608 2624 832 848 
	 [41728 41984 13312 13568]
2608 2624 848 864 
	 [41728 41984 13568 13824]
2608 2624 864 880 
	 [41728 41984 13824 14080]
2608 2624 880 896 
	 [41728 41984 14080 14336]
2608 2624 896 912 
	 [41728 41984 14336 14592]
2608 2624 912 928 
	 [41728 41984 14592 14848]
2608 2624 928 944 
	 [41728 41984 14848 15104]
2608 2624 944 960 
	 [41728 41984 15104 15360]
2608 2624 960

2656 2672 1152 1168 
	 [42496 42752 18432 18688]
2656 2672 1168 1184 
	 [42496 42752 18688 18944]
2656 2672 1184 1200 
	 [42496 42752 18944 19200]
2656 2672 1200 1216 
	 [42496 42752 19200 19456]
2656 2672 1216 1232 
	 [42496 42752 19456 19712]
2656 2672 1232 1248 
	 [42496 42752 19712 19968]
2656 2672 1248 1264 
	 [42496 42752 19968 20224]
2656 2672 1264 1280 
	 [42496 42752 20224 20480]
2656 2672 1280 1296 
	 [42496 42752 20480 20736]
2656 2672 1296 1312 
	 [42496 42752 20736 20992]
2656 2672 1312 1328 
	 [42496 42752 20992 21248]
2656 2672 1328 1344 
	 [42496 42752 21248 21504]
2656 2672 1344 1360 
	 [42496 42752 21504 21760]
2656 2672 1360 1376 
	 [42496 42752 21760 22016]
2656 2672 1376 1392 
	 [42496 42752 22016 22272]
2656 2672 1392 1408 
	 [42496 42752 22272 22528]
2656 2672 1408 1424 
	 [42496 42752 22528 22784]
2656 2672 1424 1440 
	 [42496 42752 22784 23040]
2656 2672 1440 1456 
	 [42496 42752 23040 23296]
2656 2672 1456 1472 
	 [42496 42752 23296 23552]
2656 2672 1472 1488 

2704 2720 1664 1680 
	 [43264 43520 26624 26880]
2704 2720 1680 1696 
	 [43264 43520 26880 27136]
2704 2720 1696 1712 
	 [43264 43520 27136 27392]
2704 2720 1712 1728 
	 [43264 43520 27392 27648]
2704 2720 1728 1744 
	 [43264 43520 27648 27904]
2704 2720 1744 1760 
	 [43264 43520 27904 28160]
2704 2720 1760 1776 
	 [43264 43520 28160 28416]
2704 2720 1776 1792 
	 [43264 43520 28416 28672]
2704 2720 1792 1808 
	 [43264 43520 28672 28928]
2704 2720 1808 1824 
	 [43264 43520 28928 29184]
2704 2720 1824 1840 
	 [43264 43520 29184 29440]
2704 2720 1840 1856 
	 [43264 43520 29440 29696]
2704 2720 1856 1872 
	 [43264 43520 29696 29952]
2704 2720 1872 1888 
	 [43264 43520 29952 30208]
2704 2720 1888 1904 
	 [43264 43520 30208 30464]
2704 2720 1904 1920 
	 [43264 43520 30464 30720]
2704 2720 1920 1936 
	 [43264 43520 30720 30976]
2704 2720 1936 1952 
	 [43264 43520 30976 31232]
2704 2720 1952 1968 
	 [43264 43520 31232 31488]
2704 2720 1968 1984 
	 [43264 43520 31488 31744]
2704 2720 1984 2000 

2768 2784 144 160 
	 [44288 44544  2304  2560]
2768 2784 160 176 
	 [44288 44544  2560  2816]
2768 2784 176 192 
	 [44288 44544  2816  3072]
2768 2784 192 208 
	 [44288 44544  3072  3328]
2768 2784 208 224 
	 [44288 44544  3328  3584]
2768 2784 224 240 
	 [44288 44544  3584  3840]
2768 2784 240 256 
	 [44288 44544  3840  4096]
2768 2784 256 272 
	 [44288 44544  4096  4352]
2768 2784 272 288 
	 [44288 44544  4352  4608]
2768 2784 288 304 
	 [44288 44544  4608  4864]
2768 2784 304 320 
	 [44288 44544  4864  5120]
2768 2784 320 336 
	 [44288 44544  5120  5376]
2768 2784 336 352 
	 [44288 44544  5376  5632]
2768 2784 352 368 
	 [44288 44544  5632  5888]
2768 2784 368 384 
	 [44288 44544  5888  6144]
2768 2784 384 400 
	 [44288 44544  6144  6400]
2768 2784 400 416 
	 [44288 44544  6400  6656]
2768 2784 416 432 
	 [44288 44544  6656  6912]
2768 2784 432 448 
	 [44288 44544  6912  7168]
2768 2784 448 464 
	 [44288 44544  7168  7424]
2768 2784 464 480 
	 [44288 44544  7424  7680]
2768 2784 480

2816 2832 656 672 
	 [45056 45312 10496 10752]
2816 2832 672 688 
	 [45056 45312 10752 11008]
2816 2832 688 704 
	 [45056 45312 11008 11264]
2816 2832 704 720 
	 [45056 45312 11264 11520]
2816 2832 720 736 
	 [45056 45312 11520 11776]
2816 2832 736 752 
	 [45056 45312 11776 12032]
2816 2832 752 768 
	 [45056 45312 12032 12288]
2816 2832 768 784 
	 [45056 45312 12288 12544]
2816 2832 784 800 
	 [45056 45312 12544 12800]
2816 2832 800 816 
	 [45056 45312 12800 13056]
2816 2832 816 832 
	 [45056 45312 13056 13312]
2816 2832 832 848 
	 [45056 45312 13312 13568]
2816 2832 848 864 
	 [45056 45312 13568 13824]
2816 2832 864 880 
	 [45056 45312 13824 14080]
2816 2832 880 896 
	 [45056 45312 14080 14336]
2816 2832 896 912 
	 [45056 45312 14336 14592]
2816 2832 912 928 
	 [45056 45312 14592 14848]
2816 2832 928 944 
	 [45056 45312 14848 15104]
2816 2832 944 960 
	 [45056 45312 15104 15360]
2816 2832 960 976 
	 [45056 45312 15360 15616]
2816 2832 976 992 
	 [45056 45312 15616 15872]
2816 2832 992

In [6]:
"""                                                paralell time test
need to know what size the pre-trained models used
& graphic file types preferred by tensorflow (float, float32, int, etc)
"""
PATCH_HEIGHT = 256
PATCH_WIDTH = 256
target_dir = '../../DigiPath_MLTK_data/out_to_test'

t0 = time.time()
# open the file
test_file_name = os.path.join(data_dir, 'CMU-1.svs')
print('Opening Image file: \n\t{}\n'.format(test_file_name))
os_obj = openslide.OpenSlide(test_file_name)
pixels_height = os_obj.dimensions[0]
pixels_width = os_obj.dimensions[1]

print('Image is {} x {}\n{} pixels'.format(pixels_height, 
                                           pixels_width, 
                                           pixels_height * pixels_width))

# read the meta data
pixels_height_ds = os_obj.level_dimensions[-1][0]
pixels_width_ds = os_obj.level_dimensions[-1][1]
print(pixels_height_ds, pixels_width_ds)

# find the thumbnail size ratio (need pre-trained size)
print(pixels_height / pixels_height_ds, pixels_width / pixels_width_ds)
print('obj.level_downsamples', os_obj.level_downsamples)
print('obj.level_downsamples[-1]', os_obj.level_downsamples[-1])

big_thumb = os_obj.get_thumbnail((pixels_height_ds, pixels_width_ds))
print(type(big_thumb), big_thumb.size, big_thumb.getextrema())

# make the mask
grey_thumbnail = np.array(big_thumb.convert('L'))
thresh = threshold_otsu(grey_thumbnail)
mask = np.array(grey_thumbnail) < thresh
mask_im = PIL.Image.fromarray(np.uint8(mask) * 255)
# display(mask_im)

# make the grid
grid_height = pixels_height // PATCH_HEIGHT
grid_width = pixels_width // PATCH_WIDTH
print('\n%40s: %5i, %5i'%('grid size', grid_height, grid_width))
print('%40s: %5i, %5i'%('full size cells',PATCH_HEIGHT, PATCH_WIDTH))
thumb_cell_height = pixels_height_ds // grid_height
thumb_cell_width = pixels_width_ds // grid_width
print('%40s: %5i, %5i'%('thumb cells',thumb_cell_height, thumb_cell_width))

# make the directory
_, f_name = os.path.split(test_file_name)
f_name, f_ext = os.path.splitext(f_name)
print('directory name',f_name)


"""                             N1730 Aug 28 
                            run_grid_row divides rows OK, need TFRecord per row output
                                    AND
                            TFRecord collector afterward
"""
# get the ndarrays of full size grid, write as type
def run_grid_row(run_parameters, grid_row):
    grid_height = run_parameters['grid_height']
    grid_width = run_parameters['grid_width']
    thumb_cell_height = run_parameters['thumb_cell_height']
    thumb_cell_width = run_parameters['thumb_cell_width']
    zoom_up_ratio = run_parameters['zoom_up_ratio']
    target_dir = run_parameters['target_dir']
    
    for grid_col in range(grid_width):
        h_idx_start = grid_row * thumb_cell_height
        h_idx_end = (grid_row + 1) * thumb_cell_height
        w_idx_start = grid_col * thumb_cell_width
        w_idx_end = (grid_col + 1) * thumb_cell_width
        
        big_idx = np.array([np.array([h_idx_start, h_idx_end, w_idx_start, w_idx_end]),
                            np.array([h_idx_start, h_idx_end, w_idx_start, w_idx_end]
                                    ) * zoom_up_ratio])

        s = ''
        for k in big_idx.reshape(-1):
            s += '%i'%k
        f_name = os.path.join(target_dir, hashlib.sha1(s.encode('utf-8')).hexdigest())
        with open(f_name, 'wb') as fh:
            big_idx.dump(fh)
        
zoom_up_ratio = 16
grid_row_enum = np.int_(range(0, grid_height))

temp_dirpath = tempfile.mkdtemp()
run_parameters = {'grid_height': grid_height, 
                  'grid_width': grid_width, 
                  'thumb_cell_height': thumb_cell_height, 
                  'thumb_cell_width': thumb_cell_width, 
                  'zoom_up_ratio': zoom_up_ratio, 
                  'target_dir': temp_dirpath}

n_cores = mp.cpu_count()
grid_pool = mp.Pool(processes=n_cores)
grid_pool.starmap(run_grid_row, 
                  zip(itertools.repeat(run_parameters), grid_row_enum))
grid_pool.close()
grid_pool.join()


"""                             N1730 Aug 28 
                                assemble_tmp_dir takes twice as long as run_grid_row
                                
"""
def assemble_temp_dir(run_parameters):
    target_dir = run_parameters['target_dir']
    index_array_size = grid_height * grid_width
    from_arr = np.zeros((index_array_size, 4))
    too_arr = np.zeros((index_array_size, 4))
    row_counter = 0
    for maybe_file in os.listdir(target_dir):
        maybe_full_file = os.path.join(target_dir, maybe_file)
        if os.path.isfile(maybe_full_file):
            this_mat = np.load(maybe_full_file)
            if isinstance(this_mat, np.ndarray) and this_mat.shape[0] == 2:
                from_arr[row_counter, :] = this_mat[0,:]
                too_arr[row_counter, :] = this_mat[1,:]
                row_counter += 1
                os.remove(maybe_full_file)
    print('\n\tremoved %i files'%(row_counter))
    return from_arr, too_arr

from_arr, too_arr = assemble_temp_dir(run_parameters)

try:
    print('removing', temp_dirpath)
    os.rmdir(temp_dirpath)
except:
    print(temp_dirpath, '\n directory not empty')

print('\nthumb size:', pixels_height_ds, pixels_width_ds)
print('\nfull size:', pixels_height, pixels_width)
print('%i cores available'%(n_cores))
# (save a list of files)

print('\ncell run time', time.time() - t0)

Opening Image file: 
	../../DigiPath_MLTK_data/Aperio/CMU-1.svs

Image is 46000 x 32914
1514044000 pixels
2875 2057
16.0 16.000972289742343
obj.level_downsamples (1.0, 4.000121536217793, 16.00048614487117)
obj.level_downsamples[-1] 16.00048614487117
<class 'PIL.Image.Image'> (2875, 2057) ((0, 255), (0, 255), (3, 255))

                               grid size:   179,   128
                         full size cells:   256,   256
                             thumb cells:    16,    16
directory name CMU-1

	removed 22912 files
removing /var/folders/12/rq_vvnr91sj5kh6xj64x3vsr0000gn/T/tmp5d_04y5k

thumb size: 2875 2057

full size: 46000 32914
4 cores available

cell run time 16.41913604736328


In [46]:
from_arr[0,:], too_arr[0,:]

(array([2288., 2304.,  704.,  720.]), array([36608., 36864., 11264., 11520.]))

## old code
```python
MAXPATCHESTOWRITE = 1000
import glob
import math
import os
import numpy as np
import openslide
from skimage.filters import threshold_otsu

def get_thumbnail(img, x_level0, y_level0, patch_size, output_path):
    patch = img.read_region((x_level0, y_level0), 0, (patch_size, patch_size))
    patch = patch.convert('RGB')
    fname = img.properties['aperio.Filename'].replace(' ', '_')
    fname += '_' + str(x_level0)
    fname += '_' + str(y_level0)
    fname += '_' + '0'
    fname += '_' + str(patch_size)
    fname += '.jpg'
    patch_arr = np.array(patch.convert('L'))
    if np.average(patch_arr) < 230:
        global num_patches
        num_patches += 1
        patch.save(os.path.join(output_path, fname))

def process_svs(SVS,
                normalization_factor=1000,
                patch_size=512,
                buffer=10,
                output_path=OUTPUT_PATH):
    img = openslide.OpenSlide(SVS)

    global num_patches
    num_patches = 0

    x_max, y_max = img.dimensions
    thumbnail = img.get_thumbnail((normalization_factor, normalization_factor))

    grey_thumbnail = np.array(thumbnail.convert("L"))
    thresh = threshold_otsu(grey_thumbnail)
    mask = np.array(grey_thumbnail) < thresh

    # how many pixels in the raw image per pixel in mask
    x_num_orgPix_per_thumbPix = math.ceil(x_max / mask.shape[0])
    y_num_orgPix_per_thumbPix = math.ceil(y_max / mask.shape[1])
    # print(x_num_orgPix_per_thumbPix, y_num_orgPix_per_thumbPix)

    # Find out how many pixels in image mask to count as a patch in original
    num_x_mask_pixels_per_rawPatch = math.ceil(patch_size / x_num_orgPix_per_thumbPix)
    num_y_mask_pixels_per_rawPatch = math.ceil(patch_size / y_num_orgPix_per_thumbPix)
    # print(num_x_mask_pixels_per_rawPatch, num_y_mask_pixels_per_rawPatch)

    mask_x, mask_y = mask.shape
    x_mask_prev = 0

    # Iterate through the mask to identify positive pixels
    for x in range(buffer, mask_x - buffer):
        x_mask_window = x + num_x_mask_pixels_per_rawPatch
        if x_mask_window <= x_mask_prev:
            continue
        y_mask_prev = 0
        for y in range(buffer, mask_y - buffer):
            y_mask_window = y + num_y_mask_pixels_per_rawPatch
            # print('Evaluate: {} {} & {}'.format(y, y_mask_window, y_mask_prev))
            if y_mask_window <= y_mask_prev:
                continue
            if y % 100 == 0:
                print('X: {}\tY:{} of {} with total of {} so far'.format(x, y, 
                                                                         mask.shape, 
                                                                         num_patches), end='\r',
                                                                  flush=True)
                
            if np.sum(mask[x:x_mask_window, y:y_mask_window]) > 0:
                # convert mask coordinates to level0 coordinates
                x_level0 = x * x_num_orgPix_per_thumbPix
                y_level0 = y * y_num_orgPix_per_thumbPix
                get_thumbnail(img, x_level0, y_level0, patch_size, output_path)
                
                #                                      <0><0>          Limit number of files
                if num_patches >= MAXPATCHESTOWRITE:
                    print('\n\n\t{} num_patched out\n\n'.format(num_patches))
                    return
                #                                      <0><0>

            # print('yamsk windoe: {}'.format(y_mask_window))
            y_mask_prev = y_mask_window
        x_mask_prev = x_mask_window

    print('Printed {} from {}'.format(num_patches, SVS))

num_patches = 0
"""
# if __name__ == '__main__':
#     for SVS in glob.glob('/data/biliary/svs/negative/*svs'):
#         process_svs(SVS)
"""
print('processing: {}'.format(SVS))
process_svs(SVS)
```